exports.TEXT_AND_EMOJI_LIST = [
  ['laks', 'salmon'],
  ['fisk', 'fish'],
  ['makrel', 'fish'],
  ['ørred', 'fish'],
  ['torsk', 'fish'],
  ['rødspætte', 'blowfish'],
  ['sardin', 'fish'],
  ['sild', 'fishing_pole_and_fish'],
  ['gris', 'pig2'],
  ['svine', 'pig'],
  ['flæsk', 'pig'],
  ['svin([^w]|$)', 'pig'],
  ['skinke', 'pig2'],
  ['(^| )okse', 'cow'],
  ['kalve', 'cow'],
  ['kylling', 'chicken'],
  ['astralis', 'astralis'],
  ['dota', 'dota2'],
  ['diva', 'fie'],
  ['csgo', 'csgo'],
  ['cs:go', 'csgo'],
  ['kartofler', 'potato'],
  ['kartoffel', 'potato'],
  ['hvidvin', 'wine_glass'],
  ['rødvin', 'wine_glass'],
  ['invest', 'money_with_wings'],
  ['playstation', 'playstation'],
  ['ps4', 'playstation'],
  ['burger[^r]', 'hamburger'],
  ['aubergine', 'eggplant'],
  ['kalkun', 'turkey'],
  ['bacon', 'bacon'],
  ['pasta', 'spaghetti'],
  ['spaghetti', 'spaghetti'],
  ['(^| )kage([^w]|$)', 'cake'],
  ['vandmmelon', 'watermelon'],
  ['agurk', 'cucumber'],
  ['tomat', 'tomato'],
  ['druer', 'grapes'],
  ['(dota.*lol)|(lol.*dota)', 'crossed_swords'],
  ['(dota.*csgo)|(csgo.*dota)', 'crossed_swords'],
  ['pølse', 'hotdog'],
  ['gulerod', 'carrot'],
  ['hønse', 'rooster'],
  ['kyllingelår', 'poultry_leg'],
  ['kyllinge(under|over)lår', 'poultry_leg'],
  ['drumsticks', 'poultry_leg'],
  ['(^| )kaffe', 'coffee'],
  ['æble', 'apple'],
  ['taco', 'taco'],
  ['roastbeef', 'cow'],
  ['leverpostej', 'pig2'],
  ['pizza', 'pizza'],
  ['gulerødder', 'carrot'],
  ['chili', 'hot_pepper'],
  ['chilli', 'hot_pepper'],
  ['ananas', 'pineapple'],
  ['citron', 'lemon'],
  ['lemon', 'lemon'],
  ['broccoli', 'broccoli'],
  ['wiener', 'hotdog'],
  ['honning', 'honey_pot'],
  ['coq au vin', 'hatched_chick'],
  ['appelsin', 'tangerine'],
  ['mandarin', 'tangerine'],
  ['tzatziki', 'cucumber'],
  ['banan', 'banana'],
  ['mozzarella', 'cheese_wedge'],
  ['rocket league', 'rocketleague'],
  ['(^| )rl([^w]|$)', 'rocketleague'],
  ['(^| )ea([^w]|$)', 'face_vomiting'],
  ['(^| )øl([^w]|$)', 'beer'],
  ['(^| )js([^w]|$)', 'javascript'],
  ['(^| )fie([^w]|$)', 'fie'],
  ['star.*wars', 'jarjar'],
  ['java[^s]', 'java_loading'],
  ['javascript', 'javascript'],
  ['kylle(.|)rylle', 'baby_chick'],
  ['kylle(.|)rylle()', 'hatched_chick'],
  ['kylle(.|)rylle()()', 'hatching_chick'],
  ['kylle(.|)rylle()()()', 'beers'],
  ['kylle(.|)kylle', 'x'],
  ['champignon', 'mushroom'],
  ['melon', 'melon'],
  ['vandmelon', 'watermelon'],
  ['rucola', 'green_salad'],
  ['nødder', 'peanuts'],
  ['serrano', 'it'],
  ['surimi', 'glitch_crab'],
  ['krabbe', 'crab'],
  ['parmesan', 'cheese_wedge'],
  ['kina', 'cn'],
  ['græsk', 'flag-gr'],
  ['russisk', 'flag-ru'],
  ['rusland', 'flag-ru'],
  ['italiensk', 'flag-it'],
  ['gay', 'eggplant'],
  ['fersken', 'peach'],
  ['(ikke.*teamseer)|(teamseer.*ikke)', 'triangular_flag_on_post'],
  [
    '(ikke.*compliance)|(compliance.*ikke)',
    'triangular_flag_on_post'
  ],
  ['champagne', 'champagne'],
  ['bobler', 'champagne'],
  ['rosé', 'champagne'],
  ['brut', 'champagne'],
  ['mousserende', 'champagne'],
  ['champus', 'champagne'],
  ['snaps', 'snaps'],
  ['hospital', 'hospital'],
  ['vaccine', 'syringe']
]
